"""Parse and compare the settings OrcaSlicer records in its outputs.

Three artifacts carry "the settings used", in two different encodings:

* The G-code's `; CONFIG_BLOCK_START` .. `; CONFIG_BLOCK_END` section -- one
  `; key = value` line per option, serialized by libslic3r's own option
  serializers (GCode.cpp `append_full_config`, from `print.full_print_config()`
  minus a small `banned_keys` set). This is the config the slicer *applied*.
* `Metadata/project_settings.config` inside an exported 3mf, and the file
  written by `--export-settings` -- the same `DynamicPrintConfig` saved as
  JSON (scalars as strings, vectors as lists of strings). This is the
  *merged* config before per-plate apply, so keys in the *variant* sets
  below may carry N_filaments x N_variants elements where the G-code carries
  one element per filament.

Value encodings, from libslic3r/Config.cpp:
  scalar string  -> raw text, C-style escaped (\\n \\r \\\\ \\")     [escape_string_cstyle]
  string vector  -> ';'-separated, elements quoted+escaped if they contain
                    space/tab/;/\\/"/CR/LF (or a single empty string)   [escape_strings_cstyle]
  numeric/bool/percent/point vectors -> ','-separated
The option type per key comes from cases/_snapshots/cli_surface_full.json
(generated by scripts/enumerate_cli_options.py); keys not listed there
(e.g. the `first_layer_*`/`bed_shape` extras GCode.cpp appends) are compared
as plain strings.
"""
from __future__ import annotations

import json
import re
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SURFACE_FILE = REPO_ROOT / "cases" / "_snapshots" / "cli_surface_full.json"

BLOCK_START = "; CONFIG_BLOCK_START"
BLOCK_END = "; CONFIG_BLOCK_END"

STRING_VECTOR_TYPES = {"coStrings"}
COMMA_VECTOR_TYPES = {
    "coFloats", "coInts", "coBools", "coPercents", "coFloatsOrPercents",
    "coPoints", "coPointsGroups", "coEnums",
}

# Options whose merged-config (JSON) value is expanded per extruder *variant*
# (libslic3r/PrintConfig.cpp: print_options_with_variant,
# filament_options_with_variant, printer_options_with_variant_1/_2). For these
# the JSON may hold N x V elements and the G-code the V-selected N elements,
# so the G-code vector is compared as an ordered subsequence of the JSON one.
VARIANT_KEYS = {
    # print_options_with_variant
    "initial_layer_speed", "initial_layer_infill_speed", "outer_wall_speed", "inner_wall_speed",
    "small_perimeter_speed", "small_perimeter_threshold", "sparse_infill_speed",
    "internal_solid_infill_speed", "top_surface_speed", "enable_overhang_speed",
    "overhang_1_4_speed", "overhang_2_4_speed", "overhang_3_4_speed", "overhang_4_4_speed",
    "slowdown_for_curled_perimeters", "bridge_speed", "internal_bridge_speed", "gap_infill_speed",
    "support_speed", "support_interface_speed", "travel_speed", "travel_speed_z",
    "initial_layer_travel_speed", "default_acceleration", "bridge_acceleration",
    "travel_acceleration", "initial_layer_travel_acceleration", "initial_layer_acceleration",
    "outer_wall_acceleration", "inner_wall_acceleration", "sparse_infill_acceleration",
    "internal_solid_infill_acceleration", "top_surface_acceleration", "default_jerk",
    "outer_wall_jerk", "inner_wall_jerk", "infill_jerk", "top_surface_jerk", "initial_layer_jerk",
    "travel_jerk", "initial_layer_travel_jerk", "default_junction_deviation", "print_extruder_id",
    "print_extruder_variant",
    # filament_options_with_variant
    "filament_flow_ratio", "filament_max_volumetric_speed", "filament_ramming_volumetric_speed",
    "filament_pre_cooling_temperature", "filament_ramming_travel_time",
    "filament_ramming_volumetric_speed_nc", "filament_pre_cooling_temperature_nc",
    "filament_ramming_travel_time_nc", "filament_retract_length_nc",
    "filament_preheat_temperature_delta", "filament_extruder_variant", "filament_retraction_length",
    "filament_z_hop", "filament_z_hop_types", "filament_retract_lift_above",
    "filament_retract_lift_below", "filament_retract_lift_enforce", "filament_retract_restart_extra",
    "filament_retract_length_toolchange", "filament_retract_restart_extra_toolchange",
    "filament_retraction_speed", "filament_deretraction_speed", "filament_retraction_minimum_travel",
    "filament_retract_when_changing_layer", "filament_wipe", "filament_wipe_distance",
    "filament_retract_before_wipe", "filament_retract_after_wipe",
    "filament_long_retractions_when_cut", "filament_retraction_distances_when_cut",
    "long_retractions_when_ec", "retraction_distances_when_ec", "nozzle_temperature_initial_layer",
    "nozzle_temperature", "filament_flush_volumetric_speed", "filament_flush_temp",
    "filament_cooling_before_tower", "volumetric_speed_coefficients",
    "filament_adaptive_volumetric_speed", "filament_ironing_flow", "filament_ironing_spacing",
    "filament_ironing_inset", "filament_ironing_speed", "activate_air_filtration",
    "activate_air_filtration_during_print", "activate_air_filtration_on_completion",
    "during_print_exhaust_fan_speed", "complete_print_exhaust_fan_speed",
    # printer_options_with_variant_1
    "nozzle_volume", "retraction_length", "z_hop", "travel_slope", "retract_lift_above",
    "retract_lift_below", "retract_lift_enforce", "z_hop_types", "retraction_speed",
    "deretraction_speed", "retraction_minimum_travel", "retract_when_changing_layer", "wipe",
    "wipe_distance", "retract_before_wipe", "retract_after_wipe", "retract_length_toolchange",
    "retract_restart_extra", "retract_restart_extra_toolchange", "long_retractions_when_cut",
    "retraction_distances_when_cut", "nozzle_type", "printer_extruder_id",
    "printer_extruder_variant", "hotend_cooling_rate", "hotend_heating_rate", "nozzle_flush_dataset",
    # printer_options_with_variant_2
    "machine_max_acceleration_x", "machine_max_acceleration_y", "machine_max_acceleration_z",
    "machine_max_acceleration_e", "machine_max_acceleration_extruding",
    "machine_max_acceleration_retracting", "machine_max_acceleration_travel",
    "machine_max_speed_x", "machine_max_speed_y", "machine_max_speed_z", "machine_max_speed_e",
    "machine_max_jerk_x", "machine_max_jerk_y", "machine_max_jerk_z", "machine_max_jerk_e",
    "machine_max_junction_deviation",
    # Not in the *_options_with_variant sets, but the merged config on newer builds
    # carries it expanded per filament x variant (1,1,2,2,... for 4 filaments) while
    # the G-code holds one index per filament (1,2,3,4).
    "filament_self_index",
}


def type_of(key: str) -> str | None:
    import surface

    return surface.type_map().get(key)


def is_variant_key(key: str) -> bool:
    """VARIANT_KEYS above is the fallback list (copied from one checkout); the
    live/snapshotted surface's own `variant_keys` extends it, so a newer build's
    additions are picked up without editing this file."""
    import surface

    return key in VARIANT_KEYS or key in surface.variant_keys()


# ---------------------------------------------------------------- G-code side

_LINE_RE = re.compile(r"^; ([A-Za-z0-9_]+) = (.*)$")


def extract_config_block(gcode_text: str) -> str:
    if BLOCK_START not in gcode_text:
        raise ValueError(f"{BLOCK_START!r} not found in G-code")
    after = gcode_text.split(BLOCK_START, 1)[1]
    if BLOCK_END not in after:
        raise ValueError(f"{BLOCK_END!r} not found in G-code")
    return after.split(BLOCK_END, 1)[0]


def parse_gcode_config_raw(gcode_text: str) -> dict[str, str]:
    """`; key = value` lines of the config block, values still encoded."""
    out = {}
    for line in extract_config_block(gcode_text).splitlines():
        m = _LINE_RE.match(line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


def unescape_cstyle(s: str) -> str:
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            n = s[i + 1]
            out.append({"n": "\n", "r": "\r"}.get(n, n))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def split_string_vector(s: str) -> list[str]:
    """Inverse of escape_strings_cstyle: ';'-separated, optionally quoted."""
    items, i, n = [], 0, len(s)
    if s == "":
        return []
    while i <= n:
        if i < n and s[i] == '"':
            i += 1
            buf = []
            while i < n and s[i] != '"':
                if s[i] == "\\" and i + 1 < n:
                    buf.append({"n": "\n", "r": "\r"}.get(s[i + 1], s[i + 1]))
                    i += 2
                else:
                    buf.append(s[i])
                    i += 1
            items.append("".join(buf))
            i += 1  # closing quote
        else:
            j = s.find(";", i)
            if j == -1:
                j = n
            items.append(s[i:j])
            i = j
        if i < n and s[i] == ";":
            i += 1
            if i == n:
                items.append("")
                break
        else:
            break
    return items


_UNTYPED_CSV_RE = re.compile(r"[-+0-9.%a-z_]*(,[-+0-9.%a-z_]*)+")


def decode_gcode_value(key: str, raw: str):
    t = type_of(key)
    if t in STRING_VECTOR_TYPES:
        return split_string_vector(raw)
    if t in COMMA_VECTOR_TYPES:
        return [] if raw == "" else raw.split(",")
    if t == "coString":
        return unescape_cstyle(raw)
    if t is None and _UNTYPED_CSV_RE.fullmatch(raw):
        # A few options (e.g. the nullable per-filament `filament_*_when_cut`
        # overrides) are registered outside the pattern enumerate_cli_options.py
        # scans, so they have no type here; a bare comma list of simple tokens
        # (numbers, percentages, enum names, `nil`) is unambiguously a vector.
        return raw.split(",")
    return raw


def parse_gcode_config(gcode_text: str) -> dict:
    return {k: decode_gcode_value(k, v) for k, v in parse_gcode_config_raw(gcode_text).items()}


# ------------------------------------------------------------------ JSON side

def decode_json_value(key: str, v):
    if isinstance(v, list):
        return [str(x) for x in v]
    return str(v)


def parse_settings_json(text: str) -> dict:
    return {k: decode_json_value(k, v) for k, v in json.loads(text).items()}


def read_3mf_member(path: Path, member: str) -> str:
    with zipfile.ZipFile(path) as zf:
        return zf.read(member).decode("utf-8", errors="replace")


def read_3mf_project_settings(path: Path) -> dict:
    return parse_settings_json(read_3mf_member(path, "Metadata/project_settings.config"))


def read_3mf_gcode_config(path: Path, plate: int = 1) -> dict:
    return parse_gcode_config(read_3mf_member(path, f"Metadata/plate_{plate}.gcode"))


# ------------------------------------------------------------------ compare

def _num_eq(a: str, b: str) -> bool:
    if a == b:
        return True
    try:
        return float(a.rstrip("%")) == float(b.rstrip("%")) and a.endswith("%") == b.endswith("%")
    except ValueError:
        return False


def _is_subsequence(small: list, big: list) -> bool:
    it = iter(big)
    return all(any(_num_eq(s, x) for x in it) for s in small)


# Keys whose G-code-block value is *expected* to differ from the merged JSON,
# each for a reason rooted in the slicer, not a defect of the import path:
KNOWN_DIVERGENT = {
    # GCode.cpp append_full_config() rewrites the matrix scaled by flush_multiplier
    # before writing it, so the G-code carries the effective volumes, the JSON the raw ones.
    "flush_volumes_matrix",
    # GUI-managed extruder colour; the G-code block reports the per-extruder colour
    # actually used, the merged JSON whatever the source preset/3mf carried.
    "extruder_colour",
    # Normalized at Print::apply time (forced off when a wipe tower is used), so the
    # applied value can legitimately differ from the merged one.
    "independent_support_layer_height",
    # Auto-disabled at apply time when the plate uses a single filament, so a
    # multi-filament project's merged value (1) legitimately becomes 0 in the G-code.
    "enable_prime_tower",
    # Computed during apply; GCode.cpp copies the applied value into the dump on
    # purpose ("diagnostic, nothing parses it back").
    "filament_map_2",
    # Same family on newer builds: the per-filament nozzle assignment is derived at
    # apply time (0-based in the dump, 1-based in the merged config).
    "filament_nozzle_map",
    # Preset bookkeeping, not slicing settings: string vectors whose *elements* are
    # themselves ';'-joined lists, so the G-code encoding of them is ambiguous.
    "different_settings_to_system",
    "inherits_group",
}


def values_match(key: str, gcode_val, json_val) -> bool:
    """True if a G-code block value and a merged-JSON value agree, allowing the
    documented encoding differences (numeric formatting, variant expansion,
    and the slicer padding a short per-filament vector out to filament count)."""
    if isinstance(gcode_val, str) and isinstance(json_val, list) and type_of(key) is None:
        # untyped key (not in the surface snapshot) that is evidently a vector
        gcode_val = gcode_val.split(",") if gcode_val != "" else []
    if isinstance(gcode_val, list) != isinstance(json_val, list):
        gcode_l = gcode_val if isinstance(gcode_val, list) else [gcode_val]
        json_l = json_val if isinstance(json_val, list) else [json_val]
    else:
        gcode_l, json_l = gcode_val, json_val
    if isinstance(gcode_l, list):
        if len(gcode_l) == len(json_l):
            return all(_num_eq(a, b) for a, b in zip(gcode_l, json_l))
        if len(json_l) < len(gcode_l):
            # JSON under-specified (fewer elements than filaments); the slicer pads.
            return all(_num_eq(a, b) for a, b in zip(gcode_l, json_l))
        if is_variant_key(key):
            return _is_subsequence(gcode_l, json_l)
        return False
    return _num_eq(gcode_l, json_l)


def compare_gcode_to_json(gcode_cfg: dict, json_cfg: dict, ignore: set[str] = frozenset()):
    """Return [(key, gcode_value, json_value)] for every common key that disagrees."""
    mismatches = []
    for k in sorted(set(gcode_cfg) & set(json_cfg) - set(ignore)):
        if not values_match(k, gcode_cfg[k], json_cfg[k]):
            mismatches.append((k, gcode_cfg[k], json_cfg[k]))
    return mismatches


def expect_from_preset_file(path: Path) -> dict:
    """The (key -> value) pairs a preset JSON asks for, i.e. everything except
    its own metadata. Used to derive probe expectations from a fixture file
    instead of hard-coding them in a test."""
    META = {"type", "from", "name", "inherits", "instantiation", "version", "setting_id",
            "filament_id", "compatible_printers", "compatible_prints", "compatible_printers_condition",
            "compatible_prints_condition", "is_custom_defined", "renamed_from", "upward_compatible_machine",
            "printer_model", "printer_variant", "default_print_profile", "default_filament_profile",
            "filament_settings_id", "print_settings_id", "printer_settings_id", "model_id",
            "filament_vendor", "description", "alias"}
    d = json.loads(path.read_text())
    return {k: decode_json_value(k, v) for k, v in d.items() if k not in META}
