"""Systematic config-surface fuzzing: sweep CLI options with type-appropriate
"poison" values and assert the binary doesn't crash.

This is deliberately dumber than cases/*.yaml: it doesn't know what CORRECT
behavior looks like for any given option, only that a clean CLI usage error
is fine and a SIGSEGV/SIGABRT is not. Its job is discovery, not regression
pinning -- when it finds a real crash, the next step is to isolate it by
hand (matching-value control, minimal repro) and graduate it into a proper
cases/*.yaml entry with real notes, the way nil-value-for-vector-option,
load-filaments-count-exceeds-project, and mismatched-extruder-geometry-
arrays were built this way. Don't leave a confirmed finding living only as
a fuzz failure -- a named case is what makes it a tracked regression rather
than a fact someone has to rediscover.

Coverage source: cases/_snapshots/cli_surface_full.json, generated by
    python scripts/enumerate_cli_options.py --orca-source /path/to/OrcaSlicer
which reads the option definitions directly out of PrintConfig.cpp (see that
script's docstring) instead of relying on --help, which documents only a
small fraction of what's actually accepted (see TESTING_STRATEGY.md).

By default this runs a small (25), daily-rotating-but-reproducible-within-
a-day sample so routine local/CI runs stay fast; pass --fuzz-full (slow --
hundreds of options x several poison values each) for a real sweep, meant
for a scheduled job, not every commit.
"""
import datetime
import json
import random
from pathlib import Path

from checks import no_crash

REPO_ROOT = Path(__file__).resolve().parent
SURFACE_FILE = REPO_ROOT / "cases" / "_snapshots" / "cli_surface_full.json"

# Keyed by the co* type from PrintConfig.cpp. Deliberately generic -- these
# are not tailored per-option, that's the point: coverage comes from the
# type system, not from a human having hypothesized a problem with any one
# specific option.
# "nil" into a non-nullable vector option is a known, single-root-cause abort
# class pinned by three cases (cases/crash/nil-value-*.yaml); it affects most of
# the ~235 vector options, so it is excluded here to keep the sweep hunting for
# *new* classes instead of re-finding that one every day. Re-add "nil" once the
# upstream fix lands to confirm the whole class is gone.
POISON_VALUES = {
    "coFloats": [""],
    "coInts": [""],
    "coBools": [""],
    "coPercents": [""],
    "coFloatsOrPercents": [""],
    "coEnums": ["not_a_real_value"],
    "coFloat": ["-1", "1e20", "notanumber", ""],
    "coInt": ["-1", "99999999999", "notanumber", ""],
    "coPercent": ["-1%", "notanumber", ""],
    "coFloatOrPercent": ["notanumber", ""],
    "coBool": ["2", "yes", "notabool"],
    "coEnum": ["not_a_real_value"],
    "coPoint": ["1,2,3", "notapoint", ""],
    "coPoints": ["notpoints", ""],
    "coPointsGroups": ["notgroups", ""],
    "coPoint3": ["1,2"],
    # coString/coStrings: no generically "invalid" string value worth
    # poisoning -- almost anything is a syntactically valid string. Left
    # out rather than padding the sweep with poison values unlikely to
    # find anything.
}


# (key, poison) pairs already graduated into a named cases/*.yaml entry --
# excluded here so a confirmed finding doesn't keep re-failing the fuzz
# sweep forever once it has a proper tracked case. Add to this set as part
# of graduating a finding (see this file's docstring); remove it if the
# graduated case is ever deleted.
GRADUATED = {
    ("nozzle_diameter", "nil"),  # cases/crash/nil-value-for-vector-option.yaml
    ("filament_multitool_ramming_flow", "nil"),  # cases/crash/nil-value-for-scalar-vector-option.yaml
    ("machine_max_speed_e", "nil"),  # cases/crash/nil-value-for-machine-axis-array-option.yaml
    ("printable_area", ""),  # cases/crash/empty-points-option-value-hangs.yaml (hang, not crash)
}


def _load_surface():
    import surface

    return [o for o in surface.options() if not o["nocli"]]


# (type, poison) pairs whose failure is one root cause shared by every option of
# that type and already pinned by a case -- skipped wholesale for the same reason
# as GRADUATED (see the "nil" note above POISON_VALUES).
GRADUATED_BY_TYPE = {
    ("coPoints", ""),        # cases/crash/empty-points-option-value-hangs.yaml
    ("coPointsGroups", ""),
}


def _all_cases():
    return [
        (opt["key"], opt["flag"], poison)
        for opt in _load_surface()
        for poison in POISON_VALUES.get(opt["type"], [])
        if (opt["key"], poison) not in GRADUATED and (opt["type"], poison) not in GRADUATED_BY_TYPE
    ]


def pytest_generate_tests(metafunc):
    if "fuzz_case" not in metafunc.fixturenames:
        return

    all_cases = _all_cases()
    if not all_cases:
        metafunc.parametrize("fuzz_case", [], ids=[])
        return

    if metafunc.config.getoption("--fuzz-full"):
        selected = all_cases
    else:
        sample_size = metafunc.config.getoption("--fuzz-sample")
        # Seeded by the date, not left fully random: a given day's CI run is
        # reproducible if you need to re-run it locally, but the sample
        # rotates day to day so coverage accumulates over time instead of
        # hammering the same handful of options forever.
        rng = random.Random(datetime.date.today().isoformat())
        selected = rng.sample(all_cases, min(sample_size, len(all_cases)))

    metafunc.parametrize("fuzz_case", selected, ids=[f"{key}={poison!r}" for key, _, poison in selected])


def test_fuzz(fuzz_case, run_orca, datadir, outputdir, model):
    key, flag, poison = fuzz_case
    m = model("Stanford_Bunny.3mf")
    result = run_orca(
        [f"{flag}={poison}", "--datadir", datadir, "--outputdir", outputdir, "--info", m]
    )
    no_crash(result, {})
