#!/usr/bin/env python3
"""Compare two OrcaSlicer exported .gcode.3mf (or .3mf / bare .gcode) files.

Summarizes functional differences between two sliced exports:
  * archive inventory (members present in only one file)
  * Metadata/project_settings.config — full settings diff
  * model geometry — objects, transforms (translation / rotation / scale), mesh stats
  * per-object / per-plate overrides from Metadata/model_settings.config
  * slice_info.config + plate_N.json summary values (time, filament, outside, support)
  * per-plate G-code: header block, embedded CONFIG_BLOCK, instruction stats
    (command counts, layers, z-heights, extrusion per feature, temps, fans,
    tool changes, bounding box of extruding moves), first structural divergence

Intended use: diff a CLI-sliced export against a GUI-sliced export of the same
project to find functional differences between the two paths.

Usage:
  compare_gcode3mf.py A.gcode.3mf B.gcode.3mf
  compare_gcode3mf.py --json out.json A.gcode.3mf B.gcode.3mf
  compare_gcode3mf.py --full-diff diff.txt A.gcode.3mf B.gcode.3mf
  compare_gcode3mf.py a.gcode b.gcode          # bare gcode also works

Exit codes: 0 = functionally identical, 1 = differences found, 2 = error.
Stdlib only.
"""

import argparse
import difflib
import fnmatch
import io
import json
import math
import re
import sys
import xml.etree.ElementTree as ET
import zipfile
from collections import Counter, OrderedDict

# ---------------------------------------------------------------- utilities

CORE_NS = "{http://schemas.microsoft.com/3dmanufacturing/core/2015/02}"
PROD_NS = "{http://schemas.microsoft.com/3dmanufacturing/production/2015/06}"

# Members whose contents are volatile or derived; only presence is compared.
PRESENCE_ONLY = [
    "*.png", "*.md5", "*/.rels", "_rels/.rels", "[Content_Types].xml",
]

VOLATILE_GCODE_COMMENTS = re.compile(
    r"^; generated by .* on \d{4}-\d{2}-\d{2}.*$"
)


def die(msg):
    print("error: %s" % msg, file=sys.stderr)
    sys.exit(2)


class Source:
    """A .gcode.3mf/.3mf archive, or a bare .gcode file presented as one."""

    def __init__(self, path):
        self.path = path
        self.members = OrderedDict()  # name -> bytes
        if path.endswith(".gcode"):
            with open(path, "rb") as f:
                self.members["Metadata/plate_1.gcode"] = f.read()
            self.bare_gcode = True
        else:
            try:
                zf = zipfile.ZipFile(path)
            except (zipfile.BadZipFile, OSError) as e:
                die("cannot open %s: %s" % (path, e))
            for name in zf.namelist():
                self.members[name] = zf.read(name)
            self.bare_gcode = False

    def text(self, name):
        data = self.members.get(name)
        return None if data is None else data.decode("utf-8", errors="replace")

    def names(self):
        return set(self.members)


def fmt_val(v, limit=120):
    s = json.dumps(v, ensure_ascii=False) if not isinstance(v, str) else v
    s = s.replace("\n", "\\n")
    return s if len(s) <= limit else s[: limit - 3] + "..."


# ---------------------------------------------------------------- settings diff

def flatten_settings(obj, prefix=""):
    """project_settings.config is one flat JSON object; values are strings or
    lists of strings. Flatten lists to key[i] entries for element-wise diff."""
    out = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.update(flatten_settings(v, "%s%s" % (prefix + "." if prefix else "", k)))
    elif isinstance(obj, list):
        if all(not isinstance(x, (dict, list)) for x in obj):
            if len(set(map(str, obj))) == 1 and obj:
                out[prefix + "[*]"] = str(obj[0]) + (" (x%d)" % len(obj))
            else:
                for i, v in enumerate(obj):
                    out["%s[%d]" % (prefix, i)] = str(v)
        else:
            for i, v in enumerate(obj):
                out.update(flatten_settings(v, "%s[%d]" % (prefix, i)))
    else:
        out[prefix] = str(obj)
    return out


def diff_flat(fa, fb, ignore_globs):
    def ignored(k):
        base = k.split("[")[0]
        return any(fnmatch.fnmatch(base, g) or fnmatch.fnmatch(k, g) for g in ignore_globs)

    only_a = sorted(k for k in fa if k not in fb and not ignored(k))
    only_b = sorted(k for k in fb if k not in fa and not ignored(k))
    changed = sorted(
        k for k in fa if k in fb and fa[k] != fb[k] and not ignored(k)
    )
    return only_a, only_b, changed


# ---------------------------------------------------------------- model geometry

def parse_transform_3mf(s):
    """3MF 'transform': 12 floats, row-vector convention.
    Rows 0-2 are the linear part (basis images), row 3 is translation."""
    v = [float(x) for x in s.split()]
    if len(v) != 12:
        return None
    rows = [v[0:3], v[3:6], v[6:9]]
    trans = v[9:12]
    return rows, trans


def decompose(rows, trans):
    sx = math.sqrt(sum(c * c for c in rows[0]))
    sy = math.sqrt(sum(c * c for c in rows[1]))
    sz = math.sqrt(sum(c * c for c in rows[2]))
    scale = (sx, sy, sz)
    r = [
        [rows[i][j] / scale[i] if scale[i] else 0.0 for j in range(3)]
        for i in range(3)
    ]
    trace = r[0][0] + r[1][1] + r[2][2]
    ang = math.degrees(math.acos(max(-1.0, min(1.0, (trace - 1.0) / 2.0))))
    det = (
        rows[0][0] * (rows[1][1] * rows[2][2] - rows[1][2] * rows[2][1])
        - rows[0][1] * (rows[1][0] * rows[2][2] - rows[1][2] * rows[2][0])
        + rows[0][2] * (rows[1][0] * rows[2][1] - rows[1][1] * rows[2][0])
    )
    return {
        "translation": [round(t, 4) for t in trans],
        "scale": [round(s, 5) for s in scale],
        "rotation_deg": round(ang, 3),
        "mirrored": det < 0,
    }


def mesh_stats(src, member):
    """Vertex/triangle counts and raw bbox of a 3D/Objects/*.model part."""
    txt = src.text(member)
    if txt is None:
        return None
    try:
        root = ET.fromstring(txt)
    except ET.ParseError:
        return None
    stats = {}
    for obj in root.iter(CORE_NS + "object"):
        nverts = ntris = 0
        bmin = [float("inf")] * 3
        bmax = [float("-inf")] * 3
        for vtx in obj.iter(CORE_NS + "vertex"):
            nverts += 1
            for i, axis in enumerate("xyz"):
                c = float(vtx.get(axis, "0"))
                bmin[i] = min(bmin[i], c)
                bmax[i] = max(bmax[i], c)
        for _ in obj.iter(CORE_NS + "triangle"):
            ntris += 1
        stats[obj.get("id")] = {
            "vertices": nverts,
            "triangles": ntris,
            "bbox_size": [round(bmax[i] - bmin[i], 4) for i in range(3)]
            if nverts
            else None,
        }
    return stats


def parse_model(src):
    """Object tree + build items from 3D/3dmodel.model (+ referenced parts)."""
    txt = src.text("3D/3dmodel.model")
    if txt is None:
        return None
    try:
        root = ET.fromstring(txt)
    except ET.ParseError as e:
        return {"error": "3dmodel.model parse error: %s" % e}
    model = {"metadata": {}, "objects": {}, "build": []}
    for md in root.findall(CORE_NS + "metadata"):
        model["metadata"][md.get("name")] = (md.text or "").strip()
    resources = root.find(CORE_NS + "resources")
    for obj in (resources if resources is not None else []):
        if obj.tag != CORE_NS + "object":
            continue
        oid = obj.get("id")
        entry = {"type": obj.get("type", "model"), "components": []}
        comps = obj.find(CORE_NS + "components")
        if comps is not None:
            for c in comps.findall(CORE_NS + "component"):
                path = c.get(PROD_NS + "path")
                comp = {"objectid": c.get("objectid"), "path": path}
                t = c.get("transform")
                if t:
                    parsed = parse_transform_3mf(t)
                    if parsed:
                        comp["transform"] = decompose(*parsed)
                if path:
                    ms = mesh_stats(src, path.lstrip("/"))
                    if ms:
                        comp["mesh"] = ms.get(c.get("objectid")) or next(
                            iter(ms.values()), None
                        )
                entry["components"].append(comp)
        model["objects"][oid] = entry
    build = root.find(CORE_NS + "build")
    if build is not None:
        for item in build.findall(CORE_NS + "item"):
            b = {
                "objectid": item.get("objectid"),
                "printable": item.get("printable"),
            }
            t = item.get("transform")
            if t:
                parsed = parse_transform_3mf(t)
                if parsed:
                    b["transform"] = decompose(*parsed)
            model["build"].append(b)
    return model


def parse_model_settings(src):
    """Per-object / per-part / per-plate metadata from model_settings.config."""
    txt = src.text("Metadata/model_settings.config")
    if txt is None:
        return None
    try:
        root = ET.fromstring(txt)
    except ET.ParseError as e:
        return {"error": str(e)}
    out = {"objects": {}, "plates": {}}
    for obj in root.findall("object"):
        oid = obj.get("id")
        o = {"metadata": {}, "parts": {}}
        for md in obj.findall("metadata"):
            o["metadata"][md.get("key")] = md.get("value")
        for part in obj.findall("part"):
            p = {"subtype": part.get("subtype"), "metadata": {}}
            for md in part.findall("metadata"):
                # matrix/source offsets are duplicated in 3dmodel.model
                p["metadata"][md.get("key")] = md.get("value")
            o["parts"][part.get("id")] = p
        out["objects"][oid] = o
    for plate in root.findall("plate"):
        p = {"metadata": {}, "instances": []}
        for md in plate.findall("metadata"):
            p["metadata"][md.get("key")] = md.get("value")
        for inst in plate.findall("model_instance"):
            p["instances"].append(
                {m.get("key"): m.get("value") for m in inst.findall("metadata")}
            )
        out["plates"][p["metadata"].get("plater_id", "?")] = p
    return out


def parse_slice_info(src):
    txt = src.text("Metadata/slice_info.config")
    if txt is None:
        return None
    try:
        root = ET.fromstring(txt)
    except ET.ParseError as e:
        return {"error": str(e)}
    out = {}
    for plate in root.findall("plate"):
        meta = {m.get("key"): m.get("value") for m in plate.findall("metadata")}
        idx = meta.get("index", "?")
        fils = [
            dict(f.attrib) for f in plate.findall("filament")
        ]
        out["plate_" + idx] = {"metadata": meta, "filaments": fils}
    return out


# ---------------------------------------------------------------- gcode analysis

GCODE_WORD = re.compile(r"([A-Za-z])([-+]?[0-9]*\.?[0-9]+)")


def parse_gcode(text):
    """One pass over a plate gcode: header block, config block, stats."""
    header = {}
    config = {}
    stats = {
        "total_lines": 0,
        "command_counts": Counter(),
        "layers": 0,
        "z_heights": [],
        "tool_changes": 0,
        "max_feedrate": 0.0,
        "extrusion_by_feature": Counter(),
        "travel_moves": 0,
        "extrude_moves": 0,
        "retractions": 0,
        "arc_moves": 0,
        "first_M104": None,
        "first_M140": None,
        "first_M109": None,
        "first_M190": None,
        "max_fan_speed": 0.0,
        "xy_bbox_extrude": None,
        "total_extrusion_mm": 0.0,
        "estimates": {},
    }
    in_header = in_config = False
    relative_e = False
    last_e = 0.0
    feature = "(none)"
    bmin = [float("inf")] * 2
    bmax = [float("-inf")] * 2
    x = y = None

    for raw in text.splitlines():
        stats["total_lines"] += 1
        line = raw.strip()
        if not line:
            continue
        if line.startswith(";"):
            c = line[1:].strip()
            if c == "HEADER_BLOCK_START":
                in_header = True
            elif c == "HEADER_BLOCK_END":
                in_header = False
            elif c == "CONFIG_BLOCK_START":
                in_config = True
            elif c == "CONFIG_BLOCK_END":
                in_config = False
            elif in_config:
                if " = " in c:
                    k, _, v = c.partition(" = ")
                    config[k.strip()] = v
            elif in_header:
                if ":" in c and not VOLATILE_GCODE_COMMENTS.match(line):
                    k, _, v = c.partition(":")
                    header[k.strip()] = v.strip()
            elif c.startswith("FEATURE:"):
                feature = c.split(":", 1)[1].strip()
            elif c == "CHANGE_LAYER" or c == "LAYER_CHANGE":
                stats["layers"] += 1
            elif c.startswith("Z_HEIGHT:"):
                try:
                    stats["z_heights"].append(float(c.split(":")[1]))
                except ValueError:
                    pass
            elif c.startswith(("filament used", "total filament", "estimated printing time")):
                k, sep, v = c.partition("=")
                if not sep:
                    k, sep, v = c.partition(":")
                if sep:
                    stats["estimates"][k.strip()] = v.strip()
            continue

        # executable line; strip trailing comment
        code = line.split(";", 1)[0].strip()
        if not code:
            continue
        words = dict()
        m = re.match(r"^([GMT])(\d+\.?\d*)", code)
        if not m:
            continue
        cmd = m.group(1) + m.group(2)
        stats["command_counts"][cmd] += 1
        if m.group(1) == "T":
            stats["tool_changes"] += 1
            continue
        for lw in GCODE_WORD.finditer(code[m.end():]):
            words[lw.group(1).upper()] = float(lw.group(2))
        if cmd in ("M82",):
            relative_e = False
        elif cmd in ("M83",):
            relative_e = True
        elif cmd == "G92":
            if "E" in words:
                last_e = words["E"]
        elif cmd in ("M104",) and stats["first_M104"] is None:
            stats["first_M104"] = words.get("S")
        elif cmd in ("M109",) and stats["first_M109"] is None:
            stats["first_M109"] = words.get("S")
        elif cmd in ("M140",) and stats["first_M140"] is None:
            stats["first_M140"] = words.get("S")
        elif cmd in ("M190",) and stats["first_M190"] is None:
            stats["first_M190"] = words.get("S")
        elif cmd == "M106":
            stats["max_fan_speed"] = max(stats["max_fan_speed"], words.get("S", 0.0))
        elif cmd in ("G0", "G1", "G2", "G3"):
            if cmd in ("G2", "G3"):
                stats["arc_moves"] += 1
            if "F" in words:
                stats["max_feedrate"] = max(stats["max_feedrate"], words["F"])
            de = 0.0
            if "E" in words:
                de = words["E"] if relative_e else words["E"] - last_e
                if not relative_e:
                    last_e = words["E"]
            if "X" in words:
                x = words["X"]
            if "Y" in words:
                y = words["Y"]
            if de > 0:
                stats["extrude_moves"] += 1
                stats["total_extrusion_mm"] += de
                stats["extrusion_by_feature"][feature] += de
                if x is not None and y is not None:
                    bmin[0] = min(bmin[0], x)
                    bmin[1] = min(bmin[1], y)
                    bmax[0] = max(bmax[0], x)
                    bmax[1] = max(bmax[1], y)
            elif de < 0:
                stats["retractions"] += 1
            elif "X" in words or "Y" in words or "Z" in words:
                stats["travel_moves"] += 1

    if bmin[0] != float("inf"):
        stats["xy_bbox_extrude"] = [round(v, 2) for v in bmin + bmax]
    stats["total_extrusion_mm"] = round(stats["total_extrusion_mm"], 2)
    stats["extrusion_by_feature"] = {
        k: round(v, 2) for k, v in stats["extrusion_by_feature"].items()
    }
    return header, config, stats


def normalized_stream(text):
    """Executable commands only — comments, M73 progress and blank lines
    dropped — for structural comparison."""
    out = []
    for raw in text.splitlines():
        code = raw.split(";", 1)[0].strip()
        if not code or code.startswith("M73"):
            continue
        out.append(code)
    return out


# ---------------------------------------------------------------- report

class Report:
    def __init__(self):
        self.lines = []
        self.differences = 0
        self.json = {}

    def section(self, title):
        self.lines.append("")
        self.lines.append("=" * 78)
        self.lines.append("== " + title)
        self.lines.append("=" * 78)

    def add(self, line=""):
        self.lines.append(line)

    def diff(self, line):
        self.differences += 1
        self.lines.append(line)

    def same(self, line):
        self.lines.append(line + "  [identical]")


def compare_dicts(rep, name, da, db, label_a, label_b, jkey, ignore=()):
    da = da or {}
    db = db or {}
    only_a = sorted(k for k in da if k not in db and k not in ignore)
    only_b = sorted(k for k in db if k not in da and k not in ignore)
    changed = sorted(k for k in da if k in db and da[k] != db[k] and k not in ignore)
    if not (only_a or only_b or changed):
        rep.same("%s: %d entries" % (name, len(da)))
        return
    rep.add("%s:" % name)
    for k in only_a:
        rep.diff("  - only in %s: %s = %s" % (label_a, k, fmt_val(da[k])))
    for k in only_b:
        rep.diff("  - only in %s: %s = %s" % (label_b, k, fmt_val(db[k])))
    for k in changed:
        rep.diff("  ~ %s:" % k)
        rep.add("      %s: %s" % (label_a, fmt_val(da[k])))
        rep.add("      %s: %s" % (label_b, fmt_val(db[k])))
    rep.json.setdefault(jkey, {})[name] = {
        "only_a": {k: da[k] for k in only_a},
        "only_b": {k: db[k] for k in only_b},
        "changed": {k: [da[k], db[k]] for k in changed},
    }


def main():
    ap = argparse.ArgumentParser(
        description="Summarize differences between two OrcaSlicer .gcode.3mf exports."
    )
    ap.add_argument("file_a")
    ap.add_argument("file_b")
    ap.add_argument("--label-a", default="A")
    ap.add_argument("--label-b", default="B")
    ap.add_argument(
        "--ignore",
        action="append",
        default=[],
        metavar="GLOB",
        help="settings keys to ignore (repeatable, glob ok)",
    )
    ap.add_argument("--json", metavar="FILE", help="also write machine-readable JSON")
    ap.add_argument(
        "--full-diff",
        metavar="FILE",
        help="write unified diff of normalized gcode streams",
    )
    ap.add_argument(
        "--max-context",
        type=int,
        default=6,
        metavar="N",
        help="context lines around first gcode divergence (default 6)",
    )
    args = ap.parse_args()

    A = Source(args.file_a)
    B = Source(args.file_b)
    la, lb = args.label_a, args.label_b
    rep = Report()
    rep.add("Comparing:")
    rep.add("  %s = %s" % (la, args.file_a))
    rep.add("  %s = %s" % (lb, args.file_b))

    # -- 1. archive inventory ------------------------------------------------
    rep.section("Archive inventory")
    na, nb = A.names(), B.names()
    if na == nb:
        rep.same("%d members" % len(na))
    else:
        for n in sorted(na - nb):
            rep.diff("  - only in %s: %s" % (la, n))
        for n in sorted(nb - na):
            rep.diff("  - only in %s: %s" % (lb, n))
        rep.json["members"] = {
            "only_a": sorted(na - nb),
            "only_b": sorted(nb - na),
        }

    # -- 2. project settings -------------------------------------------------
    rep.section("Project settings (Metadata/project_settings.config)")
    sa, sb = A.text("Metadata/project_settings.config"), B.text(
        "Metadata/project_settings.config"
    )
    if sa is None and sb is None:
        rep.add("not present in either file")
    elif sa is None or sb is None:
        rep.diff(
            "present only in %s" % (la if sa is not None else lb)
        )
    else:
        fa = flatten_settings(json.loads(sa))
        fb = flatten_settings(json.loads(sb))
        only_a, only_b, changed = diff_flat(fa, fb, args.ignore)
        if not (only_a or only_b or changed):
            rep.same("%d flattened keys" % len(fa))
        else:
            for k in only_a:
                rep.diff("  - key only in %s: %s = %s" % (la, k, fmt_val(fa[k])))
            for k in only_b:
                rep.diff("  - key only in %s: %s = %s" % (lb, k, fmt_val(fb[k])))
            for k in changed:
                rep.diff("  ~ %s:" % k)
                rep.add("      %s: %s" % (la, fmt_val(fa[k])))
                rep.add("      %s: %s" % (lb, fmt_val(fb[k])))
            rep.json["project_settings"] = {
                "only_a": {k: fa[k] for k in only_a},
                "only_b": {k: fb[k] for k in only_b},
                "changed": {k: [fa[k], fb[k]] for k in changed},
            }

    # -- 3. model geometry ---------------------------------------------------
    rep.section("Model geometry (3D/3dmodel.model)")
    ma, mb = parse_model(A), parse_model(B)
    if ma is None and mb is None:
        rep.add("not present in either file")
    elif ma is None or mb is None:
        rep.diff("present only in %s" % (la if ma else lb))
    else:
        oa, ob = ma["objects"], mb["objects"]
        if set(oa) != set(ob):
            rep.diff(
                "  object ids differ: %s=%s %s=%s"
                % (la, sorted(oa), lb, sorted(ob))
            )
        ja = json.dumps(ma, sort_keys=True, default=str)
        jb = json.dumps(mb, sort_keys=True, default=str)
        # per-build-item transform comparison
        for i, (ba, bb) in enumerate(zip(ma["build"], mb["build"])):
            ta, tb = ba.get("transform"), bb.get("transform")
            if ta == tb:
                rep.same(
                    "build item %d (object %s): transform %s"
                    % (i, ba.get("objectid"), fmt_val(ta))
                )
            else:
                rep.diff("  ~ build item %d (object %s) transform:" % (i, ba.get("objectid")))
                rep.add("      %s: %s" % (la, fmt_val(ta, 200)))
                rep.add("      %s: %s" % (lb, fmt_val(tb, 200)))
        if len(ma["build"]) != len(mb["build"]):
            rep.diff(
                "  build item count: %s=%d %s=%d"
                % (la, len(ma["build"]), lb, len(mb["build"]))
            )
        # mesh stats per object/component
        for oid in sorted(set(oa) & set(ob)):
            ca = oa[oid].get("components", [])
            cb = ob[oid].get("components", [])
            for j, (xa, xb) in enumerate(zip(ca, cb)):
                mma, mmb = xa.get("mesh"), xb.get("mesh")
                if mma != mmb:
                    rep.diff("  ~ object %s component %d mesh:" % (oid, j))
                    rep.add("      %s: %s" % (la, fmt_val(mma, 200)))
                    rep.add("      %s: %s" % (lb, fmt_val(mmb, 200)))
                ta, tb = xa.get("transform"), xb.get("transform")
                if ta != tb:
                    rep.diff("  ~ object %s component %d transform:" % (oid, j))
                    rep.add("      %s: %s" % (la, fmt_val(ta, 200)))
                    rep.add("      %s: %s" % (lb, fmt_val(tb, 200)))
        if ja == jb:
            rep.same("full model tree")
        rep.json["model_identical"] = ja == jb

    # -- 4. per-object / per-plate settings ---------------------------------
    rep.section("Per-object / per-plate settings (Metadata/model_settings.config)")
    msa, msb = parse_model_settings(A), parse_model_settings(B)
    if msa is None and msb is None:
        rep.add("not present in either file")
    elif msa is None or msb is None:
        rep.diff("present only in %s" % (la if msa else lb))
    else:
        for oid in sorted(set(msa["objects"]) | set(msb["objects"])):
            da = msa["objects"].get(oid, {}).get("metadata")
            db = msb["objects"].get(oid, {}).get("metadata")
            compare_dicts(
                rep, "object %s metadata" % oid, da, db, la, lb, "model_settings"
            )
            pa = msa["objects"].get(oid, {}).get("parts", {})
            pb = msb["objects"].get(oid, {}).get("parts", {})
            for pid in sorted(set(pa) | set(pb)):
                compare_dicts(
                    rep,
                    "object %s part %s metadata" % (oid, pid),
                    pa.get(pid, {}).get("metadata"),
                    pb.get(pid, {}).get("metadata"),
                    la,
                    lb,
                    "model_settings",
                )
        for plid in sorted(set(msa["plates"]) | set(msb["plates"])):
            compare_dicts(
                rep,
                "plate %s metadata" % plid,
                msa["plates"].get(plid, {}).get("metadata"),
                msb["plates"].get(plid, {}).get("metadata"),
                la,
                lb,
                "model_settings",
            )

    # -- 5. slice info -------------------------------------------------------
    rep.section("Slice results (Metadata/slice_info.config, plate_N.json)")
    ia, ib = parse_slice_info(A), parse_slice_info(B)
    if ia or ib:
        for plate in sorted(set(ia or {}) | set(ib or {})):
            compare_dicts(
                rep,
                "%s metadata" % plate,
                (ia or {}).get(plate, {}).get("metadata"),
                (ib or {}).get(plate, {}).get("metadata"),
                la,
                lb,
                "slice_info",
            )
            filsa = (ia or {}).get(plate, {}).get("filaments", [])
            filsb = (ib or {}).get(plate, {}).get("filaments", [])
            if filsa != filsb:
                rep.diff("  ~ %s filaments:" % plate)
                rep.add("      %s: %s" % (la, fmt_val(filsa, 300)))
                rep.add("      %s: %s" % (lb, fmt_val(filsb, 300)))
            else:
                rep.same("%s filaments" % plate)
    else:
        rep.add("not present in either file")
    for name in sorted(
        n for n in (A.names() | B.names()) if re.fullmatch(r"Metadata/plate_\d+\.json", n)
    ):
        ta, tb = A.text(name), B.text(name)
        if ta is None or tb is None:
            rep.diff("%s present only in %s" % (name, la if ta else lb))
            continue
        pja, pjb = json.loads(ta), json.loads(tb)
        compare_dicts(
            rep,
            name,
            flatten_settings(pja),
            flatten_settings(pjb),
            la,
            lb,
            "plate_json",
        )

    # -- 6. gcode ------------------------------------------------------------
    plates = sorted(
        n
        for n in (A.names() | B.names())
        if re.fullmatch(r"Metadata/plate_\d+\.gcode", n)
    )
    for name in plates:
        rep.section("G-code: %s" % name)
        ta, tb = A.text(name), B.text(name)
        if ta is None or tb is None:
            rep.diff("present only in %s" % (la if ta else lb))
            continue
        ha, ca, sta = parse_gcode(ta)
        hb, cb, stb = parse_gcode(tb)
        compare_dicts(rep, "header block", ha, hb, la, lb, "gcode_header")
        compare_dicts(rep, "embedded CONFIG_BLOCK", ca, cb, la, lb, "gcode_config")

        # stats
        keys = [
            "layers",
            "total_extrusion_mm",
            "extrusion_by_feature",
            "tool_changes",
            "extrude_moves",
            "travel_moves",
            "retractions",
            "arc_moves",
            "max_feedrate",
            "max_fan_speed",
            "first_M104",
            "first_M109",
            "first_M140",
            "first_M190",
            "xy_bbox_extrude",
            "estimates",
        ]
        for k in keys:
            va, vb = sta[k], stb[k]
            if va == vb:
                rep.same("%-24s %s" % (k + ":", fmt_val(va, 90)))
            else:
                rep.diff("  ~ %s:" % k)
                rep.add("      %s: %s" % (la, fmt_val(va, 200)))
                rep.add("      %s: %s" % (lb, fmt_val(vb, 200)))
        cca, ccb = sta["command_counts"], stb["command_counts"]
        if cca == ccb:
            rep.same("command counts (%d distinct commands)" % len(cca))
        else:
            rep.diff("  ~ command counts (only differing commands shown):")
            for cmd in sorted(set(cca) | set(ccb)):
                if cca.get(cmd, 0) != ccb.get(cmd, 0):
                    rep.add(
                        "      %-8s %s=%-8d %s=%d"
                        % (cmd, la, cca.get(cmd, 0), lb, ccb.get(cmd, 0))
                    )
        za, zb = sta["z_heights"], stb["z_heights"]
        if za != zb:
            rep.diff(
                "  ~ z-height sequence differs: %s has %d layers (max %s), %s has %d (max %s)"
                % (la, len(za), max(za or [0]), lb, len(zb), max(zb or [0]))
            )

        # structural comparison
        na_, nb_ = normalized_stream(ta), normalized_stream(tb)
        if na_ == nb_:
            rep.same(
                "normalized instruction stream (%d commands)" % len(na_)
            )
            rep.json.setdefault("gcode", {})[name] = {"identical": True}
        else:
            sm = difflib.SequenceMatcher(None, na_, nb_, autojunk=False)
            ratio = sm.quick_ratio()
            first = None
            for tag, i1, i2, j1, j2 in sm.get_opcodes():
                if tag != "equal":
                    first = (i1, j1)
                    break
            rep.diff(
                "  ~ instruction streams differ: %s=%d cmds, %s=%d cmds, similarity ~%.1f%%"
                % (la, len(na_), lb, len(nb_), ratio * 100)
            )
            if first:
                i, j = first
                n = args.max_context
                rep.add("    first divergence at %s cmd %d / %s cmd %d:" % (la, i, lb, j))
                for line in na_[max(0, i - 2) : i]:
                    rep.add("        %s" % line)
                for line in na_[i : i + n]:
                    rep.add("      %s> %s" % (la, line))
                for line in nb_[j : j + n]:
                    rep.add("      %s> %s" % (lb, line))
            rep.json.setdefault("gcode", {})[name] = {
                "identical": False,
                "similarity": ratio,
            }
            if args.full_diff:
                with open(args.full_diff, "w") as f:
                    f.writelines(
                        l + "\n"
                        for l in difflib.unified_diff(
                            na_, nb_, fromfile="%s:%s" % (la, name),
                            tofile="%s:%s" % (lb, name), lineterm=""
                        )
                    )
                rep.add("    full normalized diff written to %s" % args.full_diff)

    # -- other shared members not otherwise handled --------------------------
    handled = re.compile(
        r"(Metadata/(project_settings\.config|model_settings\.config|slice_info\.config|"
        r"plate_\d+\.(gcode|json|gcode\.md5))|3D/.*|_rels/.*|\[Content_Types\]\.xml|"
        r".*\.png)$"
    )
    rest = sorted(
        n for n in (A.names() & B.names()) if not handled.fullmatch(n)
    )
    if rest:
        rep.section("Other shared members")
        for n in rest:
            da, db = A.members[n], B.members[n]
            if da == db:
                rep.same(n)
            else:
                rep.diff("  ~ %s differs (%d vs %d bytes)" % (n, len(da), len(db)))
                if n.endswith((".json", ".xml", ".config")):
                    ta = da.decode("utf-8", "replace").splitlines()
                    tb = db.decode("utf-8", "replace").splitlines()
                    for line in list(
                        difflib.unified_diff(ta, tb, lineterm="", n=1)
                    )[2:12]:
                        rep.add("      %s" % line)

    # -- verdict -------------------------------------------------------------
    rep.section("Verdict")
    if rep.differences == 0:
        rep.add("FUNCTIONALLY IDENTICAL — no differences found.")
    else:
        rep.add("%d difference groups found (see sections above)." % rep.differences)
    print("\n".join(rep.lines))
    if args.json:
        rep.json["differences"] = rep.differences
        with open(args.json, "w") as f:
            json.dump(rep.json, f, indent=1, default=str)
    sys.exit(0 if rep.differences == 0 else 1)


if __name__ == "__main__":
    main()
